### ISSUE TITLE
Documentación: ¿Cómo sería el mecanismo básico?

### ISSUE THREAD

**Issue by pwqw** [hobarrera/django-mercadopago#1]
1. Creo una Preferencia.
2. Uso `.url` para armar el botón de pago.
3. Ejecuto `poll_status()` para actualizar preferencia.

¿Ese es el mecanismo básico que se espera a utilizar? ¿Hay que crear una preferencia por cada unidad de producto vendida?

**Comment by WhyNotHugo** [comment]
Más o menos sí. Cuando el cliente lo paga, sí tenés las notificaciones, el status se actualiza solo. Sino vas a tener que pollear cada tanto.

Necesitás una preferencia por cada pedido/venta, sí.

**Comment by AlexisCaffa** [comment]
Gracias! Dejo la issue abierta y la cierro cuando actualice el README.md. Sí?
Te resulta conveniente que escriba un LEEME.md en español?
